### ISSUE TITLE
Is there a way to click on the tooltip content?

### ISSUE THREAD

**Issue by LeelaBasavaiah** [rafaelquintanilha/react-linechart#14]
Currently I am using onPointHover in the LineChart and as soon as I try to to click on the tooltip the tooltip disappears as I have moved away from the point since its onPointHover. 

onPointClick does not show up the tooltip for me. I can only see the contents on console.

How do I achieve clicking on tooltip link?

Please advise.

**Comment by rafaelquintanilha** [comment]
That's not current possible, I'm afraid. If you want to make a "sticky" tooltip, you'll need to do it on your own maybe leveraging `onPointClick`. However, I'd suggest that you change your logic to redirect `onPointClick`.
