### ISSUE TITLE
Hide Labels

### ISSUE THREAD

**Issue by m4nuC** [rafaelquintanilha/react-linechart#2]
I have many use case where I'd like the labels (X, Y) to be hidden. I could do that with CSS but then it leaves an empty space withing the SVG which I can't seem to remove.
Would it make sense to add options to hide labels ?

**Comment by rafaelquintanilha** [comment]
You can hide the axis using `hideXAxis` or `hideYAxis` props or if you only want the label to be hidden, make `xLabel` and `yLabel` the empty string `""`.

**Comment by m4nuC** [comment]
Thanks but that would still leave an empty space where the `label` should be, so that doesn't work for me. 

It makes sense in many instances to not show the label, for example when showing date on an axis, it's obvious what they are

**Comment by rafaelquintanilha** [comment]
You are right, I'll consider adding new `hideXLabel` and `hideYLabel` on the next release.

**Comment by m4nuC** [comment]
Thanks. It's crucial for our use case as we only have a limited amount of space available to display the charts

**Comment by rafaelquintanilha** [comment]
Just pushed a new version (1.1.9) which contains the new `hideXLabel` and `hideYLabel`. Please update your version.

**Comment by m4nuC** [comment]
Awesome,thanks!
