### ISSUE TITLE
Show Y-value upon hovering over the points

### ISSUE THREAD

**Issue by tonyvu2014** [rafaelquintanilha/react-linechart#6]
Is there a way to show Y-value upon hovering over the points?

**Comment by rafaelquintanilha** [comment]
You can pass a custom function to `onPointHover` prop: `onPointHover={this.onPointHover}`

And then:

```
onPointHover(point) {
	return `<p><b>Y value:</b> ${point.y}</p>`;
}
```

Remember that `onPointHover` renders HTML.
